anycity/config/routes.rb
Anycity::Application.routes.draw do
  resources :cities
  root :to => 'cities#index'
end

anycity/app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :zip_code, :name
  
  def fetch_name
    url = "http://ws.geonames.org/postalCodeLookupJSON?postalcode=#{zip_code}&country=US"
    json = Net::HTTP.get_response(URI.parse(url)).body
    update_attribute(:name, JSON.parse(json)["postalcodes"].first["placeName"])
  end
end

anycity/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

anycity/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end
  
  def show
    @city = City.find(params[:id])
  end
  
  def new
    @city = City.new
  end
  
  def create
    @city = City.new(params[:city])
    if @city.save
      Stalker.enqueue("city.fetch_name", :id => @city.id)
      flash[:notice] = "Successfully created city."
      redirect_to @city
    else
      render :action => 'new'
    end
  end
  
  def edit
    @city = City.find(params[:id])
  end
  
  def update
    @city = City.find(params[:id])
    if @city.update_attributes(params[:city])
      flash[:notice] = "Successfully updated city."
      redirect_to @city
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @city = City.find(params[:id])
    @city.destroy
    flash[:notice] = "Successfully destroyed city."
    redirect_to cities_url
  end
end

anycity/app/helpers/application_helper.rb
module ApplicationHelper
end

anycity/app/helpers/cities_helper.rb
module CitiesHelper
end

anycity/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

anycity/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

anycity/app/views/cities/_form.html.erb
<%= form_for @city do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </p>
  <p><%= f.submit %></p>
<% end %>

anycity/app/views/cities/edit.html.erb
<% title "Edit City" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @city %> |
  <%= link_to "View All", cities_path %>
</p>

anycity/app/views/cities/index.html.erb
<% title "Cities" %>

<table>
  <tr>
    <th>Zip Code</th>
    <th>Name</th>
  </tr>
  <% for city in @cities %>
    <tr>
      <td><%= city.zip_code %></td>
      <td><%= city.name %></td>
      <td><%= link_to "Show", city %></td>
      <td><%= link_to "Edit", edit_city_path(city) %></td>
      <td><%= link_to "Destroy", city, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New City", new_city_path %></p>

anycity/app/views/cities/new.html.erb
<% title "New City" %>

<%= render 'form' %>

<p><%= link_to "Back to List", cities_path %></p>

anycity/app/views/cities/show.html.erb
<% title "City" %>

<p>
  <strong>Zip Code:</strong>
  <%= @city.zip_code %>
</p>
<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <%= link_to "Edit", edit_city_path(@city) %> |
  <%= link_to "Destroy", @city, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", cities_path %>
</p>

anycity/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>